# Write your MySQL query statement below
SELECT STOCK_NAME,(SUM(CASE WHEN OPERATION='SELL' THEN PRICE ELSE 0 END)-SUM(CASE WHEN OPERATION='BUY' THEN PRICE ELSE 0 END)) AS CAPITAL_GAIN_LOSS
FROM STOCKS
GROUP BY STOCK_NAME