# Write your MySQL query statement below
SELECT QUERY_NAME,ROUND(SUM(T.TOTAL)/COUNT(QUERY_NAME),2) AS QUALITY ,ROUND((SUM(RATING<3)/COUNT(RATING))*100,2) AS POOR_QUERY_PERCENTAGE
FROM( 
    SELECT QUERY_NAME,(RATING/POSITION) AS TOTAL,RATING
    FROM QUERIES
)T
GROUP BY QUERY_NAME

