# Write your MySQL query statement below
(SELECT NAME AS RESULTS
FROM MOVIERATING LEFT JOIN USERS 
ON MOVIERATING.USER_ID=USERS.USER_ID
GROUP BY MOVIERATING.USER_ID
ORDER BY COUNT(RATING) DESC,NAME ASC
LIMIT 1)

UNION ALL

(SELECT TITLE AS RESULTS
FROM MOVIERATING LEFT JOIN MOVIES
ON MOVIES.MOVIE_ID=MOVIERATING.MOVIE_ID
WHERE DATE_FORMAT(MOVIERATING.CREATED_AT, '%Y-%m') = '2020-02'
GROUP BY MOVIES.MOVIE_ID
ORDER BY SUM(RATING)/COUNT(USER_ID) DESC,TITLE ASC
LIMIT 1)

